baseURL = 'https://eric-mc2.github.io/'
languageCode = 'en-us'
title = 'Eric Chandler'

PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
googleAnalytics = "G-3XT6HHHNVY"

[params]
address = "Chicago, IL"
email = "echandle@alumni.cmu.edu"
favicon = "img/favicon.png"
firstName = "Eric"
lastName = "Chandler"
phone = "123-456-7890"
profileImage = "img/headshot.png"
showQr = false
showContact = false
showSocializations = true
#sections = ["skills","publications","creations","contributions","experience","education","blog"]
sections = ["education","experience","projects", "publications"]
math = false

[[params.handles]]
link = "https://www.linkedin.com/in/eric-mc2/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/eric-mc2/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

# Cache-busting server options
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Cache-Control = "no-cache, no-store, must-revalidate"
      Pragma = "no-cache"
      Expires = "0"

[markup]
  [markup.highlight]
    style = "friendly"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
